### ISSUE TITLE
Pitch script

### ISSUE THREAD

**Issue by Noreea** [cmsavary/my-tool#23]

**Comment by nam1962** [comment]
Voici une synthèse du parcours utilisateur pour votre pitch, étape par étape, en français :

    Page d'accueil (connexion ou inscription) : L'utilisateur ouvre la page d'accueil et voit une bannière pour se connecter ou s'inscrire. S'ils ne sont pas connectés, ils peuvent cliquer sur les liens "Se connecter" ou "S'inscrire" pour continuer.

    Inscription d'un utilisateur : Si l'utilisateur choisit de s'inscrire, il sera redirigé vers la page d'inscription où il pourra créer un nouveau compte.

    Connexion d'un utilisateur : Si l'utilisateur choisit de se connecter, il sera redirigé vers la page de connexion où il pourra entrer son email et son mot de passe.

    Page d'index des outils : Une fois connecté, l'utilisateur est dirigé vers la page d'index où il peut voir une liste de tous les outils disponibles.

    Page de détails d'un outil : L'utilisateur peut cliquer sur un outil spécifique pour voir ses détails.

    Page de réservation : Sur la page de détails de l'outil, l'utilisateur peut cliquer sur un bouton "Louer" qui le mène à la page de réservation. Ici, il peut choisir les dates de location de l'outil.

    Confirmation de réservation : Après avoir soumis le formulaire de réservation, l'utilisateur est redirigé vers la page d'index des outils avec un message de confirmation, indiquant que sa réservation a été effectuée avec succès.

Ce parcours utilisateur couvre le processus, depuis l'accès à la page d'accueil jusqu'à la réservation réussie d'un outil.

**Comment by nam1962** [comment]
Voici un schéma en Markdown avec les liens pour représenter le parcours utilisateur :

    [Page d'accueil](https://www.phind.com/)

    [Connexion](https://www.phind.com/users/sign_in)
    [Inscription](https://www.phind.com/users/sign_up)

    [Inscription d'un utilisateur](https://www.phind.com/users/sign_up)

    Création d'un compte

    [Connexion d'un utilisateur](https://www.phind.com/users/sign_in)

    Saisie de l'email et du mot de passe

    [Page d'index des outils](https://www.phind.com/tools)

    Liste des outils disponibles

    [Page de détails d'un outil](https://www.phind.com/tools/:id)

    Affichage des informations de l'outil
    [Bouton "Louer"](https://www.phind.com/tools/:id/bookings/new)

    [Page de réservation](https://www.phind.com/tools/:id/bookings/new)

    Choix des dates de location
    Soumission du formulaire de réservation

    [Confirmation de réservation](https://www.phind.com/tools)

    Retour à la page d'index des outils
    Message de confirmation

**Comment by nam1962** [comment]
Étape | Description | Lien
-- | -- | --
1 | Page d'accueil | /
1.1 | Connexion | /users/sign_in
1.2 | Inscription | /users/sign_up
2 | Inscription d'un utilisateur | /users/sign_up
3 | Connexion d'un utilisateur | /users/sign_in
4 | Page d'index des outils | /tools
5 | Page de détails d'un outil | /tools/:id
5.1 | Bouton "Louer" | /tools/:id/bookings/new
6 | Page de réservation | /tools/:id/bookings/new
7 | Confirmation de réservation | /tools

Étape	Description	Lien
1	Page d'accueil	[/](https://www.phind.com/)
1.1	Connexion	[/users/sign_in](https://www.phind.com/users/sign_in)
1.2	Inscription	[/users/sign_up](https://www.phind.com/users/sign_up)
2	Inscription d'un utilisateur	[/users/sign_up](https://www.phind.com/users/sign_up)
3	Connexion d'un utilisateur	[/users/sign_in](https://www.phind.com/users/sign_in)
4	Page d'index des outils	[/tools](https://www.phind.com/tools)
5	Page de détails d'un outil	[/tools/:id](https://www.phind.com/tools/:id)
5.1	Bouton "Louer"	[/tools/:id/bookings/new](https://www.phind.com/tools/:id/bookings/new)
6	Page de réservation	[/tools/:id/bookings/new](https://www.phind.com/tools/:id/bookings/new)
7	Confirmation de réservation	[/tools](https://www.phind.com/tools)
